<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.1.310
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Miten voin auttaa Form -lähetys',
	'heading' => 'Uuden lomakkeen lähetys',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Valittu',
		'checkbox_unchecked' => 'Ei valittu',
		'submitted_from' => 'Lomake lähetetty sivustosta:%s',
		'submitted_by' => 'Kävijän IP-osoite:%s',
		'too_many_submissions' => 'Liian monta viimeaikaista lähetystä tästä IP-osoitteesta',
		'failed_to_send_email' => 'Sähköpostin lähetys epäonnistui',
		'invalid_reCAPTCHA_private_key' => 'Yksityinen reCAPTCHA-avain ei kelpaa.',
		'invalid_field_type' => 'Tuntematon kentän tyyppi %s.',
		'invalid_form_config' => 'Kentässä %s on virheellinen määritys.',
		'unknown_method' => 'Tuntematon palvelinpyyntötapa'
	),
	'email' => array(
		'from' => 'kiia.pitkanen@gmail.com',
		'to' => 'kiia.pitkanen@gmail.com'
	),
	'fields' => array(
		'custom_U318' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nimi',
			'required' => true,
			'errors' => array(
				'required' => 'Kenttä Nimi on pakollinen.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Sähköposti',
			'required' => true,
			'errors' => array(
				'required' => 'Kenttä Sähköposti on pakollinen.',
				'format' => 'Kentässä Sähköposti on virheellinen sähköpostiosoite.'
			)
		),
		'custom_U324' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Viesti',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U332' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Yritys',
			'required' => true,
			'errors' => array(
				'required' => 'Kenttä Yritys on pakollinen.'
			)
		)
	)
);

process_form($form);
?>
